{% set name = "napari-annotatorj" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-annotatorj-{{ version }}.tar.gz
  sha256: 8f5b01c01b12c6e310651c8b7a3d69e53c8c59d673b8b558d2e163e2ef6bbed3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - imagecodecs
    - keras
    - napari-plugin-engine >=0.1.4
    - numpy
    - opencv >=4.5.5
    - python >={{ python_min }}
    - roifile
    - scikit-image
    - tensorflow >=2.5.0
    - tifffile
    - qtpy
    - napari
    - tqdm

test:
  imports:
    - napari_annotatorj
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/spreka/napari-annotatorj
  summary: The napari adaptation of the ImageJ/Fiji plugin AnnotatorJ for easy image annotation.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - spreka
    - goanpeca
    - jaimergp
